set-option -g status-style bg=#232831  # good for terra fox

set -g default-terminal "tmux-256color"
# Start panes as non-login shells to prevent path_helper from duplicating PATH entries
set -g default-command "${SHELL}"
set -g mouse on
set-option -g focus-events on

# Auto-source local .tmux.conf files
if-shell '[ -f .tmux.conf ]' 'source-file .tmux.conf'

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind g display-popup -E -xC -yC -w 90% -h 90% -d "#{pane_current_path}" lazygit

set -s command-alias[100] init-triwin='run-shell "~/.config/tmux/scripts/label-windows.sh"'

# create a scratch session that I can bind to when I want
bind -n 'C-\' if-shell -F '#{==:#{session_name},scratch}' \
  'switch-client -l' \
  'new-session -A -d -s scratch -c ~/Coding/scratch ; switch-client -t =scratch'
